# .markdownlint.yaml ─ configuration for markdownlint-cli

# Start with every default rule enabled
default: true

# disable the line-length rule completely
MD013: false

# MD029 – ordered-list numbering style
MD029:
  # Accept real 1-2-3 numbering instead of forcing every item to “1.”
  style: ordered
